Added Guren No Yumiya
anshumanv/ongaku pull request #110
Opened 2017-09-02 11:05 UTC by Lucifer24

2017-09-02 15:58 UTC, anshumanv reviewed
Check comments

2017-09-02 15:58 UTC, Anshuman-Verma commented on js/data.json
> -		"link" : "http://67.159.62.2/anime_ost/gintama-op5-single-donten/ettjaclvre/01%20-%20Donten.mp3",
Why is this line getting removed ?

2017-09-03 06:13 UTC, anshumanv requested changes
Please put new additions at the end of the array

2017-09-03 06:24 UTC, Lucifer24 commented
@Anshuman-Verma there was a reason i did that.

2017-09-03 06:25 UTC, Anshuman-Verma commented
What reason ?

2017-09-03 06:30 UTC, Lucifer24 commented
@Anshuman-Verma i think its fine now

2017-09-03 08:50 UTC, Anshuman-Verma commented
Image ain't good, I'll send link shortly

2017-09-03 08:52 UTC, Anshuman-Verma commented
Use this https://k43.kn3.net/taringa/D/D/8/D/C/6/t_good/767.jpg

2017-09-03 12:31 UTC, anshumanv approved these changes

2017-09-03 12:31 UTC, merged